name: Merge Dependabot PRs
on:
  pull_request:
    types:
      - opened

jobs:
  merge_dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Merge pull request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const octokit = github.getOctokit(token);
            await octokit.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              reviewer: [context.repo.owner],
            });
